/* Generated by Together */

package javapattern.design.isp;

public class RdbIndexer implements Indexer
{
    public void reIndexAll()
    {
    	//write your code here
    }

    public void updateIndex()
    {
    	//write your code here
    }
}
